from sqlalchemy.orm import Session
from . import models, schemas



# ==========================================
# 1. APP CONFIG OPERATIONS
# ==========================================

def get_apps(db: Session, skip: int = 0, limit: int = 100):
    return db.query(models.AppConfig).offset(skip).limit(limit).all()

def get_app(db: Session, app_id: int):
    # This fetches the App, AND because of relationships, 
    # it fetches all Pages, Inputs, and Calculations automatically when accessed.
    return db.query(models.AppConfig).filter(models.AppConfig.id == app_id).first()


def create_app(db: Session, app: schemas.AppConfigCreate):
    # 1. Create the model instance
    db_app = models.AppConfig(**app.dict())
    # 2. Add to session
    db.add(db_app)
    # 3. Commit (Save to DB)
    db.commit()
    # 4. Refresh (Get the ID generated by the DB)
    db.refresh(db_app)
    return db_app

def delete_app(db: Session, app_id: int):
    db_app = get_app(db, app_id)
    if db_app:
        db.delete(db_app)
        db.commit()
    return db_app


# ==========================================
# 2. PAGE OPERATIONS (The Smart Part)
# ==========================================

def create_page_for_app(db: Session, app_id: int, page_data: schemas.PageCreate):
    """
    Creates a Page, AND creates all the Inputs/Calculations inside it 
    in one single transaction.
    """
    
    # 1. Separate the nested data (inputs/calcs) from the main page data
    # We use .dict() to convert Pydantic model to dictionary
    page_dict = page_data.dict()
    
    # Remove the lists so we can create the Page object first
    inputs_data = page_dict.pop("inputs", []) 
    calculations_data = page_dict.pop("calculations", [])

    # 2. Create the Page Object
    db_page = models.Page(**page_dict, config_id=app_id)
    
    # 3. "Deep Create" - Add the inputs
    for input_item in inputs_data:
        # Create InputVariable model and add to the relationship list
        new_input = models.InputVariable(**input_item) 
        db_page.inputs.append(new_input) # SQLAlchemy Magic: handles foreign keys for you!

    # 4. "Deep Create" - Add the calculations
    for calc_item in calculations_data:
        new_calc = models.Calculation(**calc_item)
        db_page.calculations.append(new_calc)

    # 5. Save everything at once
    db.add(db_page)
    db.commit()
    db.refresh(db_page)
    return db_page

# NOT GONNA BE USED
def get_page(db: Session, page_id: int):
    return db.query(models.Page).filter(models.Page.id == page_id).first()

def delete_page(db: Session, page_id: int):
    db_page = get_page(db, page_id)
    if db_page:
        db.delete(db_page)
        db.commit()
    return db_page


# ==========================================
# 3. USER OPERATIONS (Basic)
# ==================

def get_page_calculations(db: Session, app_id: int, page_id: int):
    return (
        db.query(models.Calculation)
        .join(models.Page) # Join calculations to their parent page
        .filter(models.Page.id == page_id)        # Must match the requested page
        .filter(models.Page.config_id == app_id)  # Must belong to the requested app
        .all()
    )